// src/app/destination-card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-destination-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './destination-card.component.html',
  styleUrls: ['./destination-card.component.css']
})
export class DestinationCardComponent {
  @Input() destination: any;
}

<div class="card h-100 border-0 shadow destination-card position-relative overflow-hidden">
  <img [src]="destination.imageUrl" [alt]="destination.city + ', ' + destination.country" class="card-img destination-img position-absolute w-100 h-100 object-fit-cover" />
  <div class="card-img-overlay d-flex flex-column justify-content-end p-3 bg-dark bg-opacity-25">
    <div>
      <h5 class="card-title text-white fw-bold">{{ destination.city }}</h5>
      <div class="d-flex justify-content-between align-items-center mt-1">
        <span class="text-white-50 small">{{ destination.country }}</span>
        <span class="fw-bold text-white">From <span class="text-primary">{{ destination.price }}</span></span>
      </div>
    </div>
  </div>
</div>

// react/src/components/DestinationCard.tsx

import { Link } from "react-router-dom";

interface DestinationCardProps {
  city: string;
  country: string;
  imageUrl: string;
  price: string;
  link: string;
}

const DestinationCard = ({ city, country, imageUrl, price, link }: DestinationCardProps) => {
  return (
    <Link to={link} className="group block">
      <div className="relative rounded-lg overflow-hidden shadow-md h-[280px]">
        <img
          src={imageUrl}
          alt={`${city}, ${country}`}
          className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-110"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent" />
        
        <div className="absolute bottom-0 left-0 w-full p-4 text-white">
          <h3 className="text-xl font-bold">{city}</h3>
          <div className="flex justify-between items-center mt-1">
            <p className="text-sm text-white/80">{country}</p>
            <p className="font-bold text-white">
              From <span className="text-secondary">{price}</span>
            </p>
          </div>
        </div>
      </div>
    </Link>
  );
};

export default DestinationCard;
