// src/app/home-hero.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-home-hero',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './home-hero.component.html',
  styleUrls: ['./home-hero.component.css']
})
export class HomeHeroComponent {
  @Input() goToLogin: () => void = () => {};
  @Input() goToSignup: () => void = () => {};
}

<section class="position-relative w-100">
  <div class="bg-primary bg-gradient text-white d-flex align-items-center justify-content-center" style="height: 400px; background-image: url('https://images.unsplash.com/photo-1469041797191-50ace28483c3?auto=format&fit=crop&w=2000&q=80'); background-size: cover; background-position: center;">
    <div class="position-absolute top-0 start-0 w-100 h-100" style="background: rgba(0,0,0,0.4);"></div>
    <div class="position-relative z-1 text-center w-100">
      <h1 class="display-4 fw-bold mb-3 text-white text-shadow">Discover the World with TripEase</h1>
      <p class="lead text-white-50 mb-4">Find and book the best deals on flights, hotels, and vacation packages</p>
      <button class="btn btn-primary me-2" (click)="goToLogin()">Login</button>
      <button class="btn btn-outline-light" (click)="goToSignup()">Sign Up</button>
    </div>
  </div>
</section>

// react/src/components/HomeHero.tsx

const HomeHero = () => {
  return (
    <div className="relative">
      {/* Hero Background */}
      <div 
        className="bg-gradient-to-r from-primary-600 to-primary-400 h-[500px] md:h-[400px]"
        style={{
          backgroundImage: `url('https://images.unsplash.com/photo-1469041797191-50ace28483c3?auto=format&fit=crop&w=2000&q=80')`,
          backgroundSize: 'cover',
          backgroundPosition: 'center',
        }}
      >
        <div className="absolute inset-0 bg-black/40" />
        <div className="relative container mx-auto px-4 h-full flex flex-col items-center justify-center text-center z-10">
          <h1 className="text-4xl md:text-5xl font-bold text-white mb-4 animate-fade-in">
            Discover the World with TripEase
          </h1>
          <p className="text-lg md:text-xl text-white/90 max-w-2xl mb-8 animate-fade-in">
            Find and book the best deals on flights, hotels, and vacation packages
          </p>
        </div>
      </div>
    </div>
  );
};

export default HomeHero;
