// src/app/offer-card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-offer-card',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './offer-card.component.html',
  styleUrls: ['./offer-card.component.css']
})
export class OfferCardComponent {
  @Input() offer: any;
}

<div class="card h-100 border-0 shadow offer-card position-relative overflow-hidden">
  <img [src]="offer.imageUrl" [alt]="offer.title" class="card-img offer-img position-absolute w-100 h-100 object-fit-cover" />
  <div class="card-img-overlay d-flex flex-column justify-content-between p-3 bg-dark bg-opacity-50">
    <div>
      <span class="badge bg-primary mb-2">{{ offer.discount }}</span>
      <h5 class="card-title text-white fw-bold">{{ offer.title }}</h5>
      <p class="card-text text-white-50 small">{{ offer.description }}</p>
    </div>
    <a [routerLink]="offer.link" class="btn btn-outline-light btn-sm align-self-start mt-2">Book Now</a>
  </div>
</div>

// react/src/components/OfferCard.tsx

import { ArrowRight } from "lucide-react";
import { Link } from "react-router-dom";

interface OfferCardProps {
  title: string;
  description: string;
  imageUrl: string;
  discount: string;
  link: string;
}

const OfferCard = ({ title, description, imageUrl, discount, link }: OfferCardProps) => {
  return (
    <div className="group relative rounded-lg overflow-hidden shadow-md hover:shadow-xl transition-all duration-300 flex h-[200px]">
      <img
        src={imageUrl}
        alt={title}
        className="absolute inset-0 h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"
      />
      <div className="absolute inset-0 bg-black/50 group-hover:bg-black/60 transition-all duration-300" />
      
      <div className="relative h-full w-full p-6 flex flex-col justify-between text-white z-10">
        <div>
          <div className="inline-block px-3 py-1 mb-3 bg-secondary rounded-md text-sm font-bold">
            {discount}
          </div>
          <h3 className="text-xl font-bold mb-1">{title}</h3>
          <p className="text-sm text-white/80">{description}</p>
        </div>
        
        <Link 
          to={link} 
          className="flex items-center text-sm font-medium text-white hover:text-secondary transition-colors"
        >
          Book Now <ArrowRight size={16} className="ml-1" />
        </Link>
      </div>
    </div>
  );
};

export default OfferCard;
